### PR TITLE
🦤 UPDATE - went through jenkins to correct versions etc 🪄

### PR DESCRIPTION
**Pull request by springdo**
(🧟) 🦤

Went through the plugins for Jenkins compatable with 2.414.3, got the build running currently and the plugins loading without missing deps etc. Jenkins looks happier but will let you know if it fails. Opening the PR now before I go anymore insane checking plugin versions against dependencies against the version of Jenkins 

🧟🧟🧟

### CODE REVIEW

**Comment by springdo** [comment]
(as per comment on here https://github.com/rht-labs/s2i-config-jenkins/pull/46)

**Comment by springdo** [comment]
Tested and verified using a demo system provided cluster (ocp 4.12) - all plugins working fine against this version of jenkins, no angry UPDATE THIS or THIS IS DEPRICATED blah blah

If you try using this on a 4.14 base image using a 4.12 cluster it will not work. I found out the hard way .... 

image

FYI @ckavili / @eformat

**Comment by eformat** [comment]
Good stuff .. hmm.. think the tl500 demo.redhat is still on 4.12... nightly test suite on 4.13 

Shall we merge this and get the demo version on newer openshift? Think that's good way ⏩⏩

@springdo @ckavili

**Comment by springdo** [comment]
I would say we merge as @tdbeattie and @dmytri are doing a TL500 in Vienna next week..... Likely using the Demo platform as the GLS stuff is 👖 . I guess they just need to make sure the https://github.com/rht-labs/tech-exercise/blob/main/ubiquitous-journey/values-tooling.yaml#L49 is set to 4.12 for this to work end to end. @eformat can you show us how you have the nightlys and the dmeo system setup? I would like to see how we can share the updating etc

**Comment by eformat** [comment]
Will hit the merge button ✅
Demo yup can do.. it checks the steps applied.. but needs more work to make it into the 3rd chapter

**Review by eformat — APPROVED** [review]
Lgtm

**Pull request merged**
