### PR TITLE
Improvements to the seed job

### PR DESCRIPTION
**Pull request by springdo**
Just about to start a residency and pushing some changes to the seed job to allow GitLab webhooks trigger the branch scanning. This means no more 1 min delay or periodic checking.

### CODE REVIEW

**Comment by mcanoy** [comment]
@springdo this has been sitting for awhile. I'm assuming you still want to add this. Maybe @jacobsee could do a review?

**Comment by jacobsee** [comment]
I have this spun up, but what is the best way to test it? I don't see much documentation on `computedFolderWebHookTrigger`.

**Comment by springdo** [comment]
yeah i'd like this slotted in alright, easiest way to test it is with an instance of GitLab. Or just accept that the plugin is working as it should ...🤷‍♂ .... 😀 !

But in all seriousness, the Token that is set in the call signature for the plugin is usually set in GitLab same way we set the token in the enablement instructions for triggering builds.
https://rht-labs.github.io/enablement-docs/#/2-attack-of-the-pipelines/README?id=part-1-explore-the-todo-list-app

**Review by jacobsee — APPROVED** [review]
Sorry for the delay - looks good!

**Pull request merged**
