### PR TITLE
🧨 Feature/latest plugins nov23 🧨

### PR DESCRIPTION
**Pull request by eformat**
this updates ALL jenkins plugins to latest versions.
this works with 4.14 jenkins origin image OK (at least jenkins starts and the Ex.1+2 tests run in TL500)
i have not confirmed its all kosher though in terms of every plugin (there are 170+ of them)
but would like to get TL500 nightly tests working again (currently disabled and broken as jenkins pod will not start).
and then run through it properly from the start 🎉🎉

### CODE REVIEW

**Comment by ckavili** [comment]
alright, let's see what the nightly test will say:) thanks a lot @eformat , you rock! 🚀

**Comment by eformat** [comment]
@ckavili thanks !! 🪄🪄

looks good - https://github.com/rht-labs/tech-exercise/actions/runs/6790332582

**Comment by ckavili** [comment]
Ahh can't believe you beat me to it! I was about to write about it 🙈 thanks for updating the plugins again!!

**Comment by springdo** [comment]
Just spun this guy up in the the demo system - ran teamsters to deploy it all up to ex2... Jenkins looks fine according to the build on the home page etc 
image


but there is no actual build having happened. 
image

 I see loads of plugin errors on hte plugin page though ... I'll investigate.... And here was me thinking i'd finally get those e2e tests done ... 😉

**Comment by ckavili** [comment]
me searching for e2e tests:
image

**Pull request merged**
